### ISSUE TITLE
couldn't get test to run after adding eslinting rules

### ISSUE THREAD

**Issue by ravi005e** [jdavis61/webdriverio-typescript-examples#3]
just c;loned your project 
[webdriverio-typescript-examples.zip](https://github.com/jdavis61/webdriverio-typescript-examples/files/6307443/webdriverio-typescript-examples.zip)
and added rules, see attached file.  thanks for help

**Comment by ravi005e** [comment]
got it work in ff

**Comment by jdavis61** [comment]
@ravi005e thanks for letting me know, I will update the dependencies and fix.
